import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Dashboard | Dukaan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-inter">
        <div className="flex justify-center">
          <div className=" max-w-[1440px] w-full flex min-h-screen">
            <SideBar />
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
